### ISSUE TITLE
ImportError: cannot import name 'cumtrapz' from 'scipy.integrate'

### ISSUE THREAD

**Issue by anindyaganguly19** [nikhil-sarin/redback#220] opened 2024-07-06 13:19 UTC
I have installed redback from source (from requirements.txt) with the development mode. But while importing redback, I faced an import error from the scipy module. I checked the new name of this method cumulative_trapezoid. 
It will also be helpful if I get some version info of the packages in the requirements.txt file, such as the NumPy module.

**Comment by nikhil-sarin** [comment] 2024-07-06 18:17
Hi, thanks. I'm aware of the issue and will fix it soon. The problem is with the name change in scipy.

**Comment by nikhil-sarin** [comment] 2024-07-09 14:51
@anindyaganguly19 - this should be fixed now by #221. I am closing this issue now; please feel free to open it if it's not resolved for you.

**Closed by nikhil-sarin** 2024-07-09 14:51 UTC
